version: '2'
services:
    rabbitmq:
        image: rabbitmq:3.6-management
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - /var/lib/rabbitmq
        restart: unless-stopped
    postgres:
        image: postgres:9.6-alpine
        ports:
            - "5432:5432"
        volumes:
            - /var/lib/postgresql/data
        restart: unless-stopped
    oracle:
        image: wnameless/oracle-xe-11g-r2
        ports:
            - "1521:1521"
        volumes:
            - /u01/app/oracle/oradata
            - /u01/app/oracle/admin
            - /u01/app/oracle/fast_recovery_area
        restart: unless-stopped
    mongo:
        image: mongo:3.4
        ports:
            - "27017:27017"
        volumes:
            - /var/lib/mongodb
        restart: unless-stopped
    haproxy:
        image: haproxy:1.7
        ports:
            - "1234:1234"
        volumes:
            - /c/projects/proxies/localhost/etc/haproxy:/usr/local/etc/haproxy/
        environment: 
            - COMPUTERNAME
        restart: unless-stopped


