version: '2'
services:
    rabbitmq:
        image: rabbitmq:3.6-management
        ports: 
            - "5672:5672"
            - "15672:15672"
        volumes: 
            - /var/lib/rabbitmq
    postgres:
        image: postgres:9.6-alpine
        ports:
            - "5432:5432"
        volumes:
            - /var/lib/postgresql/data