version: '2'
services:
    rabbitmq:
        image: rabbitmq:3.6-management
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - /var/lib/rabbitmq
    postgres:
        image: postgres:9.6-alpine
        ports:
            - "5432:5432"
        volumes:
            - /var/lib/postgresql/data
    oracle:
        image: wnameless/oracle-xe-11g
        ports:
            - "1521:1521"
        volumes:
            - /u01/app/oracle/oradata
            - /u01/app/oracle/admin
            - /u01/app/oracle/fast_recovery_area
    mongo:
      image: mongo:3.4
      ports:
          - "27017:27017"
      volumes:
          - /var/lib/mongodb

    haproxy:
      image: haproxy:1.7
      network_mode: "host"
      volumes:
          - /c/projects/proxies/localhost/etc/haproxy:/usr/local/etc/haproxy/



